stages:
  - build
  - test

image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

cache:
  paths:
    - .m2/repository/
      
test:
  stage: test
  tags:
    - ubuntu:22.04
  script:
    - mvn $MAVEN_CLI_OPTS test
  rules:
    - if: '$CI_COMMIT_REF_NAME != "master" && $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'

build:
  stage: build
  tags:
    - ubuntu:22.04
  script:
    - mvn $MAVEN_CLI_OPTS compile
  rules:
    - if: '$CI_COMMIT_REF_NAME != "master" && $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'

